### ISSUE TITLE
[GTP Context] Some words are incorrectly changed to "[Name]" when it should not

### ISSUE THREAD

**Issue by RubenOussoren** [RubenOussoren/projects#1]
## This is to improve filtering text for context gathering.

Examples

Before text was filtered:
```
Time Frame - Specific Dates & Times (when issue started/stopped; frequency)
NA
Please link to any relevant slack conversations here
NA
More Information (Browser/OS, Device, Troubleshooting Steps Performed, Theme)
NA

Splunk is index=nginx blocked_by_waf_rule=abs client_ip=[IP] | top limit=10 uri 
```

After text was filtered:

```
Time Frame - Specific Dates & Times (when issue started/stopped; frequency)
[Name]
Please link to any relevant slack conversations here
[Name]
More Information (Browser/[Name], Device, Troubleshooting [Name], Theme)
[Name]
  
Splunk is index=nginx blocked_by_waf_rule=abs client_ip=[[Name]] | top limit=10 uri
```

**Comment by Phil-Hall-Shopify** [comment]
It may be that when two words begin with an uppercase letter: e.g.`Example Here`, they can sometimes be filtered as a `[Name]`. An example of this here:
![Image of some non-names being filtered](https://screenshot.click/25-02-g14uk-jqgsj.png)

**Comment by RubenOussoren** [comment]
This issue has been resolved by adding a `TrieNode` class that helped speed up how names are searched in a large library. The `preload_names.js` contains around `~25,750` names that will be used to filter any name related PII when context is copied from Zendesk Tickets. This list can also easily be updated with more data if needed.
