### ISSUE TITLE
[GPT Context] Empty notes are appearing in some results

### ISSUE THREAD

**Issue by Phil-Hall-Shopify** [RubenOussoren/projects#2]
Example of behavior here:

<img width="717" alt="example3" src="https://user-images.githubusercontent.com/82771278/234346361-65a9f990-f4e3-4b4b-b181-b2e11e546fa9.png">

Example ticket of behavior here: first 14 notes appeared as empty:

ZD #37627199

**Comment by RubenOussoren** [comment]
This issue has been resolved inadvertently from fixing the [[GTP Context] Some words are incorrectly changed to "[Name]" when it should not](https://github.com/RubenOussoren/projects/issues/1) issue
